# Generated by Django 5.2.6 on 2025-09-23 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                ("message", models.TextField(help_text="Email message content")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("job_opportunity", "Job Opportunity"),
                            ("interview_request", "Interview Request"),
                            ("follow_up", "Follow Up"),
                            ("general", "General Inquiry"),
                            ("rejection", "Rejection"),
                        ],
                        default="general",
                        help_text="Type of email being sent",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="Job title if this email is related to a specific position",
                        max_length=200,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company name if this email is from a specific company",
                        max_length=200,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The candidate receiving the email",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="The recruiter sending the email",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-sent_at"],
            },
        ),
    ]
