# Generated by Django 5.2.6 on 2025-09-23 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="A brief professional headline (e.g., 'Senior Software Engineer')",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A brief description about yourself and your career goals",
                        max_length=1000,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "skills",
                    models.TextField(
                        help_text="List your key skills separated by commas (e.g., Python, Django, React, SQL)"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        help_text="List your educational background (e.g., 'BS Computer Science - Georgia Tech, 2023')"
                    ),
                ),
                (
                    "work_experience",
                    models.TextField(
                        help_text="Describe your work experience, including company names, positions, and key achievements"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="Your LinkedIn profile URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="Your GitHub profile URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True,
                        help_text="Your portfolio or personal website URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "other_url",
                    models.URLField(
                        blank=True,
                        help_text="Any other relevant URL (e.g., personal blog, Stack Overflow)",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
