# Generated by Django 5.0 on 2025-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow recruiters to find and view your profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_bio',
            field=models.BooleanField(default=True, help_text='Display your bio on your public profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Display your education history on your public profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True, help_text='Display your professional links to recruiters.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_location',
            field=models.BooleanField(default=True, help_text='Display your location on your public profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Display your phone number so recruiters can contact you directly.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_work_experience',
            field=models.BooleanField(default=True, help_text='Display your work experience on your public profile.'),
        ),
    ]
