# Generated by Django 5.0 on 2025-10-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOC, or DOCX format)', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_resume',
            field=models.BooleanField(default=True, help_text='Allow recruiters to download your resume.'),
        ),
    ]
