# Generated by Django 5.0 on 2025-10-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_resume_profile_show_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commute_radius',
            field=models.PositiveIntegerField(default=50, help_text='Preferred commute radius in miles (default: 50 miles)'),
        ),
    ]
