# Generated by Django 5.0 on 2025-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_savedcandidatesearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedcandidatesearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='savedcandidatesearch',
            name='last_match_count',
        ),
        migrations.RemoveField(
            model_name='savedcandidatesearch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savedcandidatesearch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='savedcandidatesearch',
            name='last_notified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savedcandidatesearch',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
