# Generated by Django 5.0 on 2025-10-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0003_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Link to the actual job posting (if available)', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
