# Generated by Django 5.0.14 on 2025-09-23 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job title (e.g., 'Senior Software Engineer')", max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('location', models.CharField(help_text="Job location (e.g., 'Atlanta, GA' or 'Remote')", max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('description', models.TextField(help_text='Detailed job description including responsibilities and requirements')),
                ('requirements', models.TextField(help_text='Required skills, experience, and qualifications')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks offered (optional)')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (optional)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (optional)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline (optional)', null=True)),
                ('external_url', models.URLField(blank=True, help_text='External application URL (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
