# Generated by Django 5.0.14 on 2025-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Comma-separated list of required skills (e.g., Python, Django, React)'),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='Does this position offer visa sponsorship?'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', help_text='Work arrangement (on-site, remote, or hybrid)', max_length=20),
        ),
    ]
